name: TWRP Build - Tecno CL8
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Sync TWRP Source
        run: |
          mkdir ~/twrp && cd ~/twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-14.1
          repo sync -j$(nproc --all)

      - name: Build Recovery Image
        run: |
          cd ~/twrp
          ln -s $GITHUB_WORKSPACE device/tecno/CL8
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch twrp_CL8-eng
          mka recoveryimage -j$(nproc --all)

      - name: Upload TWRP
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-Tecno-CL8
          path: ~/twrp/out/target/product/CL8/*.img
          
