DEVICE_PATH := device/tecno/CL8

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic

# Kernel Details (Base sa Tecno CL8)
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_BASE          := 0x00000000
BOARD_KERNEL_OFFSET        := 0x00008000
BOARD_RAMDISK_OFFSET       := 0x00000000
BOARD_VENDOR_RAMDISK_OFFSET := 0x01100000
BOARD_TAGS_OFFSET          := 0x00000100
BOARD_INCLUDE_RECOVERY_DTBO := true

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144
TARGET_NO_RECOVERY := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

# TWRP Specifics
TW_THEME := portrait_hdpi
TW_USE_TOOLBOX := true
TW_INCLUDE_CRYPTO := true
  
